### PR TITLE
Patch setup.py to remove install_requires

### LINKED ISSUE #1: vitables installation problem
Hi,
the qtpy dependency is giving installation problems to some users (see https://github.com/uvemas/ViTables/issues/75). I haven't experienced the problem when installing directly the package, but if a vitables environment is created first and then the package is installed then the problem appears. Would it be possible to add this dependency to the meta.yaml file and see if it fixes the problem?

Thanks

### PR DESCRIPTION
**Pull request by rth**
An attempt to fix #1 and #3 by,
 -  patching `setup.py` to remove the `install_requres` line
 -  adding the requirement versions to `recepe/meta.yaml`
 - additionally testing the import of `vitables.utils`

cc @scopatz @uvemas Please let me know if there is a better approach...

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @rth this seems like the right approach to me!

**Comment by rth** [comment]
Thanks @scopatz ! Any suggestions on how I could debug the failing patch? It works fine on my machine using the same command:
```
/usr/bin/patch -p1 -i recipe/patches/0001-Remove-install_requires-from-setup.py.patch
```

 I thought it was related to CRLF/LF issue as suggested in https://github.com/conda-forge/planarity-feedstock/issues/1#issuecomment-279162457 (setup.py is CRLF while the patch was originally LF) but converting the patch to CRLF with `.gitattributes` doesn't seem to help and CircleCi was still failing...

Detailed log below,
```
Downloading https://github.com/uvemas/ViTables/archive/v3.0.0.tar.gz
Success
Applying patch: '/recipe_root/patches/0001-Remove-install_requires-from-setup.py.patch'
patching file setup.py
Hunk #1 FAILED at 49.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/patch', '-p1', '-i', '/recipe_root/patches/0001-Remove-install_requires-from-setup.py.patch']' returned non-zero exit status 1.
```

**Comment by rth** [comment]
@scopatz Replaced patching of `setup.py` with `pip install --no-deps . ` as suggested by @mivade . CI now passes and this PR ready to be reviewed ... Thanks!

**Comment by rth** [comment]
Further tests show that `pip install --no-deps` does not seem to be fully equivalent to removing the `install_requires` line: in this case pip indeed does not attempt to check dependencies at install-time, but they are still checked at run time and running e.g., in a Py3.5 conda virtual env 
```
pip install --no-deps -https://github.com/uvemas/ViTables/archive/v3.0.0.tar.gz
```
still produces an error when starting ViTables same as in https://github.com/conda-forge/vitables-feedstock/issues/1   (removing the `install_requires` line doesn't produce this error). I can't find any other relevant options for `pip` or `setup.py`, so I guess this means this PR is back to trying to make patching work..

**Comment by uvemas** [comment]
OMG! I didn't expect this to be so difficult :(

**Comment by scopatz** [comment]
Hi @rth - thanks for keeping this going.  I think patching is fine, if that is what is working right now.

**Comment by uvemas** [comment]
Hi @rth, if patching keeps failing may be something similar to the solution proposed in [#75](https://github.com/uvemas/ViTables/issues/75) (near the end of the thread) could be useful here.

**Comment by rth** [comment]
@uvemas Yeah, I was also thinking that this would have already been done with a simple find and replace (e.g. using `sed`, etc).. But patching is a cleaner way of doing it, and it was half working previously (on windows by not Linux). It must be some small Linux/Windows file formatting compatibility issue. I'll look into it this weekend..

**Comment by mikofski** [comment]
two ideas, actually three:

1. @uvemas and @rth I really like @wbagdon idea to just [add another conda specific `setup.py` file without the `install_requires` lines](../../../uvemas/ViTables/issues/75#issuecomment-315390088) as short term fix, obviously it's a PITA to have double source, and it's obviously not DRY, but it's short term. Then replace the `python setup.py ...` line in the `meta.yaml` recipe file with: `python setup-conda.py ...`

2. @scopatz and @ccordoba12 IMHO this PyQt5 thing is a real problem. Again IMHO I don't think that [anaconda3 issue 1554](../../../ContinuumIO/anaconda-issues/issues/1554) should have been closed.

    * I think a short term fix should be to add something to the conda-forge documents to make sure that  new recipes remove any dependencies from `setup.py` to pyqt5
    * I think the @conda-forge-linter should check for the presence of pyqt5 in `install_requires` of the `setup.py` file and flag the recipe if it exists with a pointer to the documentation
    * I kinda like @ankostis idea to make a dummy pyqt5 package that does nothing, but is installed by the pyqt recipe so that you don't get the pkg-resources error and pip won't try to install pyqt5 over the conda-forge/anaconda pyqt recipe. Ugh!

**Comment by mikofski** [comment]
Sorry for adding onto a closed PR/issue, perhaps I should open a new one? I can't remember how I got this working last time, but I just reinstalled miniconda, and now this is not working for me, or perhaps I have a new problem? I can install vitables-3.0.0-2 from conda-forge, but vitables.exe wont start, I just get this cryptic window:
vitables

Here are my qt from conda

|qt|ver|src|
|--|--|--|
|pyqt |5.6.0 |py36_5    conda-forge|
|qt |5.6.2 |vc14_1  [vc14]  conda-forge|
|qtpy |1.4.0 |py36_0    conda-forge|
|sip|4.18| py36_1    conda-forge

If I start it by running
`python %LOCALAPPDATA%\Continuum\miniconda3\envs\py36\Lib\site-packages\vitables\start.py`

then I get this traceback:

<details>

```
(py36) C:\Users\mikm>python %LOCALAPPDATA%\Continuum\miniconda3\envs\py36\Lib\site-packages\vitables\start.py
2018-04-17 17:12:07,347 - vitables.h5db.dbstreemodel - INFO - Creating the Query results file...
2018-04-17 17:12:08,254 - vitables.preferences.pluginsloader - ERROR - Failed to load plugin: vitables.plugins.columnorg.columnar_org
2018-04-17 17:12:08,255 - vitables.preferences.pluginsloader - ERROR - The 'PyQt5>=5.5.1' distribution was not found and is required by the application
2018-04-17 17:12:08,597 - vitables.preferences.pluginsloader - ERROR - Failed to load plugin: vitables.plugins.dbstreesort.dbs_tree_sort
2018-04-17 17:12:08,597 - vitables.preferences.pluginsloader - ERROR - The 'PyQt5>=5.5.1' distribution was not found and is required by the application
2018-04-17 17:12:08,934 - vitables.preferences.pluginsloader - ERROR - Failed to load plugin: vitables.plugins.csv.export_csv
2018-04-17 17:12:08,935 - vitables.preferences.pluginsloader - ERROR - The 'PyQt5>=5.5.1' distribution was not found and is required by the application
2018-04-17 17:12:09,270 - vitables.preferences.pluginsloader - ERROR - Failed to load plugin: vitables.plugins.csv.import_csv
2018-04-17 17:12:09,271 - vitables.preferences.pluginsloader - ERROR - The 'PyQt5>=5.5.1' distribution was not found and is required by the application
2018-04-17 17:12:09,608 - vitables.preferences.pluginsloader - ERROR - Failed to load plugin: vitables.plugins.timeseries.time_series
2018-04-17 17:12:09,609 - vitables.preferences.pluginsloader - ERROR - The 'PyQt5>=5.5.1' distribution was not found and is required by the application
```

</details>

but it _does_ open, so this is success? Seems like the error is, that it doesn't detect PyQt even though I can import from `qtpy` from within python.

This also works, with the same errors tho: `python -c "from vitables import start;start.gui()"` or from inside a python interpreter it does the same, but only if I have the conda-forge pyqt-5.6.0.

Another oddity, if I have the _Anaconda_ version of pyqt-5.6.0, then when I try: `from vitables.start import gui` or `from vitables import start` python just crashes, no traceback, nothing. Weird.

**Comment by scopatz** [comment]
Maybe this needs to be rerendered to match the new packages.  I'll try that.

**Comment by scopatz** [comment]
I have rerendered the feedstock in #5.  Hopefully this fixes the issue.  A new package should be available soon.

**Pull request merged**
